global:
  smtp_smarthost: smtp.exmail.qq.com:465 # 发件人邮箱smtp地址
  smtp_auth_username: meng.gao@inforefiner.com # 发件人邮箱账号
  smtp_from: meng.gao@inforefiner.com # 发件人邮箱账号
  smtp_auth_password: password # 发件人邮箱密码
  resolve_timeout: 5m
  smtp_require_tls: false
route:
  # group_by: ['alertname'] # 报警分组依据
  group_wait: 10s # 最初即第一次等待多久时间发送一组警报的通知
  group_interval: 10s # 在发送新警报前的等待时间
  repeat_interval: 20m # 发送重复警报的周期 对于email配置中多频繁
  receiver: 'email'
receivers:
- name: email
  email_configs:
  - send_resolved: true
    to: admin1@inforefiner.com # 收件人邮箱账号
