version: '2'

networks:
    monitor:
        driver: bridge


services:

    prometheus:
        image: prom/prometheus:v2.39.2
        container_name: prometheus
        hostname: prometheus
        user: root
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./data/prometheus:/prometheus
            - ./rules:/etc/prometheus/rules
        ports:
            - "9090:9090"
        networks:
            - monitor
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--storage.tsdb.retention.time=3d"
            - "--web.enable-lifecycle"
            - "--log.level=debug"

    alertmanager:  #预警模块
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        restart: always
        ports:
            - "9093:9093"
        volumes:
            - ./data/alertmanager:/alertmanager/data
            - ./alertmanager.yml:/alertmanager.yml
        command:
            - "--config.file=/alertmanager.yml"
        networks:
            - monitor

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        user: root
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
            - ./data/grafana:/var/lib/grafana
        networks:
            - monitor

    node-exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        hostname: node-exporter
        restart: always
        ports:
            - "9100:9100"
        networks:
            - monitor


    blackbox-exporter:
        image: prom/blackbox-exporter
        container_name: blackbox-exporter
        hostname: blackbox-exporter
        ports:
            - 9115:9115
        command:
            - "--config.file=/etc/blackbox-exporter/blackbox.yml"
        volumes:
            - "./blackbox.yml:/etc/blackbox-exporter/blackbox.yml"
        networks:
            - monitor
